package com.sh.vehiclemanagement.demo.service;

import com.sh.vehiclemanagement.demo.entity.VehicleEntity;

public interface VehicleService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int deleteByID(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int insert(VehicleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int insertSelective(VehicleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    VehicleEntity selectByID(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int updateSelective(VehicleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int update(VehicleEntity record);
}
