package com.sh.vehiclemanagement.demo.entity;

import com.sh.base.entity.BaseEntity;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class VehicleEntity extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleLicence
     *
     * @mbggenerated
     */
    private String vehiclelicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleOwner
     *
     * @mbggenerated
     */
    private String vehicleowner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehiclePurchaseTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date vehiclepurchasetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleBrand
     *
     * @mbggenerated
     */
    private String vehiclebrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleModel
     *
     * @mbggenerated
     */
    private String vehiclemodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleColor
     *
     * @mbggenerated
     */
    private String vehiclecolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleSeating
     *
     * @mbggenerated
     */
    private Integer vehicleseating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleType
     *
     * @mbggenerated
     */
    private String vehicletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleAddress
     *
     * @mbggenerated
     */
    private String vehicleaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleUseCharacter
     *
     * @mbggenerated
     */
    private String vehicleusecharacter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleEngineNo
     *
     * @mbggenerated
     */
    private String vehicleengineno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleVin
     *
     * @mbggenerated
     */
    private String vehiclevin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleFileNo
     *
     * @mbggenerated
     */
    private String vehiclefileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleExamineExpires
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date vehicleexamineexpires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleAnnualTicketExpires
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date vehicleannualticketexpires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleAndVesselTaxExpires
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date vehicleandvesseltaxexpires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleInsuranceExpires
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date vehicleinsuranceexpires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.Creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.Changer
     *
     * @mbggenerated
     */
    private Integer changer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.ChangeTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date changetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.remark1
     *
     * @mbggenerated
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleExamineExpiresNotifyCount
     *
     * @mbggenerated
     */
    private Integer vehicleexamineexpiresnotifycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleAnnualTicketExpiresNotifyCount
     *
     * @mbggenerated
     */
    private Integer vehicleannualticketexpiresnotifycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleAndVesselTaxExpiresNotifyCount
     *
     * @mbggenerated
     */
    private Integer vehicleandvesseltaxexpiresnotifycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.VehicleInsuranceExpiresNotifyCount
     *
     * @mbggenerated
     */
    private Integer vehicleinsuranceexpiresnotifycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.mail1
     *
     * @mbggenerated
     */
    private String mail1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.mail2
     *
     * @mbggenerated
     */
    private String mail2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.mail3
     *
     * @mbggenerated
     */
    private String mail3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.mail4
     *
     * @mbggenerated
     */
    private String mail4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiclevanagement.mailcount
     *
     * @mbggenerated
     */
    private Integer mailcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.id
     *
     * @return the value of vehiclevanagement.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.id
     *
     * @param id the value for vehiclevanagement.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleLicence
     *
     * @return the value of vehiclevanagement.VehicleLicence
     *
     * @mbggenerated
     */
    public String getVehiclelicence() {
        return vehiclelicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleLicence
     *
     * @param vehiclelicence the value for vehiclevanagement.VehicleLicence
     *
     * @mbggenerated
     */
    public void setVehiclelicence(String vehiclelicence) {
        this.vehiclelicence = vehiclelicence == null ? null : vehiclelicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleOwner
     *
     * @return the value of vehiclevanagement.VehicleOwner
     *
     * @mbggenerated
     */
    public String getVehicleowner() {
        return vehicleowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleOwner
     *
     * @param vehicleowner the value for vehiclevanagement.VehicleOwner
     *
     * @mbggenerated
     */
    public void setVehicleowner(String vehicleowner) {
        this.vehicleowner = vehicleowner == null ? null : vehicleowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehiclePurchaseTime
     *
     * @return the value of vehiclevanagement.VehiclePurchaseTime
     *
     * @mbggenerated
     */
    public Date getVehiclepurchasetime() {
        return vehiclepurchasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehiclePurchaseTime
     *
     * @param vehiclepurchasetime the value for vehiclevanagement.VehiclePurchaseTime
     *
     * @mbggenerated
     */
    public void setVehiclepurchasetime(Date vehiclepurchasetime) {
        this.vehiclepurchasetime = vehiclepurchasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleBrand
     *
     * @return the value of vehiclevanagement.VehicleBrand
     *
     * @mbggenerated
     */
    public String getVehiclebrand() {
        return vehiclebrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleBrand
     *
     * @param vehiclebrand the value for vehiclevanagement.VehicleBrand
     *
     * @mbggenerated
     */
    public void setVehiclebrand(String vehiclebrand) {
        this.vehiclebrand = vehiclebrand == null ? null : vehiclebrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleModel
     *
     * @return the value of vehiclevanagement.VehicleModel
     *
     * @mbggenerated
     */
    public String getVehiclemodel() {
        return vehiclemodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleModel
     *
     * @param vehiclemodel the value for vehiclevanagement.VehicleModel
     *
     * @mbggenerated
     */
    public void setVehiclemodel(String vehiclemodel) {
        this.vehiclemodel = vehiclemodel == null ? null : vehiclemodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleColor
     *
     * @return the value of vehiclevanagement.VehicleColor
     *
     * @mbggenerated
     */
    public String getVehiclecolor() {
        return vehiclecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleColor
     *
     * @param vehiclecolor the value for vehiclevanagement.VehicleColor
     *
     * @mbggenerated
     */
    public void setVehiclecolor(String vehiclecolor) {
        this.vehiclecolor = vehiclecolor == null ? null : vehiclecolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleSeating
     *
     * @return the value of vehiclevanagement.VehicleSeating
     *
     * @mbggenerated
     */
    public Integer getVehicleseating() {
        return vehicleseating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleSeating
     *
     * @param vehicleseating the value for vehiclevanagement.VehicleSeating
     *
     * @mbggenerated
     */
    public void setVehicleseating(Integer vehicleseating) {
        this.vehicleseating = vehicleseating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleType
     *
     * @return the value of vehiclevanagement.VehicleType
     *
     * @mbggenerated
     */
    public String getVehicletype() {
        return vehicletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleType
     *
     * @param vehicletype the value for vehiclevanagement.VehicleType
     *
     * @mbggenerated
     */
    public void setVehicletype(String vehicletype) {
        this.vehicletype = vehicletype == null ? null : vehicletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleAddress
     *
     * @return the value of vehiclevanagement.VehicleAddress
     *
     * @mbggenerated
     */
    public String getVehicleaddress() {
        return vehicleaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleAddress
     *
     * @param vehicleaddress the value for vehiclevanagement.VehicleAddress
     *
     * @mbggenerated
     */
    public void setVehicleaddress(String vehicleaddress) {
        this.vehicleaddress = vehicleaddress == null ? null : vehicleaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleUseCharacter
     *
     * @return the value of vehiclevanagement.VehicleUseCharacter
     *
     * @mbggenerated
     */
    public String getVehicleusecharacter() {
        return vehicleusecharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleUseCharacter
     *
     * @param vehicleusecharacter the value for vehiclevanagement.VehicleUseCharacter
     *
     * @mbggenerated
     */
    public void setVehicleusecharacter(String vehicleusecharacter) {
        this.vehicleusecharacter = vehicleusecharacter == null ? null : vehicleusecharacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleEngineNo
     *
     * @return the value of vehiclevanagement.VehicleEngineNo
     *
     * @mbggenerated
     */
    public String getVehicleengineno() {
        return vehicleengineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleEngineNo
     *
     * @param vehicleengineno the value for vehiclevanagement.VehicleEngineNo
     *
     * @mbggenerated
     */
    public void setVehicleengineno(String vehicleengineno) {
        this.vehicleengineno = vehicleengineno == null ? null : vehicleengineno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleVin
     *
     * @return the value of vehiclevanagement.VehicleVin
     *
     * @mbggenerated
     */
    public String getVehiclevin() {
        return vehiclevin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleVin
     *
     * @param vehiclevin the value for vehiclevanagement.VehicleVin
     *
     * @mbggenerated
     */
    public void setVehiclevin(String vehiclevin) {
        this.vehiclevin = vehiclevin == null ? null : vehiclevin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleFileNo
     *
     * @return the value of vehiclevanagement.VehicleFileNo
     *
     * @mbggenerated
     */
    public String getVehiclefileno() {
        return vehiclefileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleFileNo
     *
     * @param vehiclefileno the value for vehiclevanagement.VehicleFileNo
     *
     * @mbggenerated
     */
    public void setVehiclefileno(String vehiclefileno) {
        this.vehiclefileno = vehiclefileno == null ? null : vehiclefileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleExamineExpires
     *
     * @return the value of vehiclevanagement.VehicleExamineExpires
     *
     * @mbggenerated
     */
    public Date getVehicleexamineexpires() {
        return vehicleexamineexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleExamineExpires
     *
     * @param vehicleexamineexpires the value for vehiclevanagement.VehicleExamineExpires
     *
     * @mbggenerated
     */
    public void setVehicleexamineexpires(Date vehicleexamineexpires) {
        this.vehicleexamineexpires = vehicleexamineexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleAnnualTicketExpires
     *
     * @return the value of vehiclevanagement.VehicleAnnualTicketExpires
     *
     * @mbggenerated
     */
    public Date getVehicleannualticketexpires() {
        return vehicleannualticketexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleAnnualTicketExpires
     *
     * @param vehicleannualticketexpires the value for vehiclevanagement.VehicleAnnualTicketExpires
     *
     * @mbggenerated
     */
    public void setVehicleannualticketexpires(Date vehicleannualticketexpires) {
        this.vehicleannualticketexpires = vehicleannualticketexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleAndVesselTaxExpires
     *
     * @return the value of vehiclevanagement.VehicleAndVesselTaxExpires
     *
     * @mbggenerated
     */
    public Date getVehicleandvesseltaxexpires() {
        return vehicleandvesseltaxexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleAndVesselTaxExpires
     *
     * @param vehicleandvesseltaxexpires the value for vehiclevanagement.VehicleAndVesselTaxExpires
     *
     * @mbggenerated
     */
    public void setVehicleandvesseltaxexpires(Date vehicleandvesseltaxexpires) {
        this.vehicleandvesseltaxexpires = vehicleandvesseltaxexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleInsuranceExpires
     *
     * @return the value of vehiclevanagement.VehicleInsuranceExpires
     *
     * @mbggenerated
     */
    public Date getVehicleinsuranceexpires() {
        return vehicleinsuranceexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleInsuranceExpires
     *
     * @param vehicleinsuranceexpires the value for vehiclevanagement.VehicleInsuranceExpires
     *
     * @mbggenerated
     */
    public void setVehicleinsuranceexpires(Date vehicleinsuranceexpires) {
        this.vehicleinsuranceexpires = vehicleinsuranceexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.Creator
     *
     * @return the value of vehiclevanagement.Creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.Creator
     *
     * @param creator the value for vehiclevanagement.Creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.Changer
     *
     * @return the value of vehiclevanagement.Changer
     *
     * @mbggenerated
     */
    public Integer getChanger() {
        return changer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.Changer
     *
     * @param changer the value for vehiclevanagement.Changer
     *
     * @mbggenerated
     */
    public void setChanger(Integer changer) {
        this.changer = changer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.ChangeTime
     *
     * @return the value of vehiclevanagement.ChangeTime
     *
     * @mbggenerated
     */
    public Date getChangetime() {
        return changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.ChangeTime
     *
     * @param changetime the value for vehiclevanagement.ChangeTime
     *
     * @mbggenerated
     */
    public void setChangetime(Date changetime) {
        this.changetime = changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.remark1
     *
     * @return the value of vehiclevanagement.remark1
     *
     * @mbggenerated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.remark1
     *
     * @param remark1 the value for vehiclevanagement.remark1
     *
     * @mbggenerated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.Remark
     *
     * @return the value of vehiclevanagement.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.Remark
     *
     * @param remark the value for vehiclevanagement.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleExamineExpiresNotifyCount
     *
     * @return the value of vehiclevanagement.VehicleExamineExpiresNotifyCount
     *
     * @mbggenerated
     */
    public Integer getVehicleexamineexpiresnotifycount() {
        return vehicleexamineexpiresnotifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleExamineExpiresNotifyCount
     *
     * @param vehicleexamineexpiresnotifycount the value for vehiclevanagement.VehicleExamineExpiresNotifyCount
     *
     * @mbggenerated
     */
    public void setVehicleexamineexpiresnotifycount(Integer vehicleexamineexpiresnotifycount) {
        this.vehicleexamineexpiresnotifycount = vehicleexamineexpiresnotifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleAnnualTicketExpiresNotifyCount
     *
     * @return the value of vehiclevanagement.VehicleAnnualTicketExpiresNotifyCount
     *
     * @mbggenerated
     */
    public Integer getVehicleannualticketexpiresnotifycount() {
        return vehicleannualticketexpiresnotifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleAnnualTicketExpiresNotifyCount
     *
     * @param vehicleannualticketexpiresnotifycount the value for vehiclevanagement.VehicleAnnualTicketExpiresNotifyCount
     *
     * @mbggenerated
     */
    public void setVehicleannualticketexpiresnotifycount(Integer vehicleannualticketexpiresnotifycount) {
        this.vehicleannualticketexpiresnotifycount = vehicleannualticketexpiresnotifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleAndVesselTaxExpiresNotifyCount
     *
     * @return the value of vehiclevanagement.VehicleAndVesselTaxExpiresNotifyCount
     *
     * @mbggenerated
     */
    public Integer getVehicleandvesseltaxexpiresnotifycount() {
        return vehicleandvesseltaxexpiresnotifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleAndVesselTaxExpiresNotifyCount
     *
     * @param vehicleandvesseltaxexpiresnotifycount the value for vehiclevanagement.VehicleAndVesselTaxExpiresNotifyCount
     *
     * @mbggenerated
     */
    public void setVehicleandvesseltaxexpiresnotifycount(Integer vehicleandvesseltaxexpiresnotifycount) {
        this.vehicleandvesseltaxexpiresnotifycount = vehicleandvesseltaxexpiresnotifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.VehicleInsuranceExpiresNotifyCount
     *
     * @return the value of vehiclevanagement.VehicleInsuranceExpiresNotifyCount
     *
     * @mbggenerated
     */
    public Integer getVehicleinsuranceexpiresnotifycount() {
        return vehicleinsuranceexpiresnotifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.VehicleInsuranceExpiresNotifyCount
     *
     * @param vehicleinsuranceexpiresnotifycount the value for vehiclevanagement.VehicleInsuranceExpiresNotifyCount
     *
     * @mbggenerated
     */
    public void setVehicleinsuranceexpiresnotifycount(Integer vehicleinsuranceexpiresnotifycount) {
        this.vehicleinsuranceexpiresnotifycount = vehicleinsuranceexpiresnotifycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.mail1
     *
     * @return the value of vehiclevanagement.mail1
     *
     * @mbggenerated
     */
    public String getMail1() {
        return mail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.mail1
     *
     * @param mail1 the value for vehiclevanagement.mail1
     *
     * @mbggenerated
     */
    public void setMail1(String mail1) {
        this.mail1 = mail1 == null ? null : mail1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.mail2
     *
     * @return the value of vehiclevanagement.mail2
     *
     * @mbggenerated
     */
    public String getMail2() {
        return mail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.mail2
     *
     * @param mail2 the value for vehiclevanagement.mail2
     *
     * @mbggenerated
     */
    public void setMail2(String mail2) {
        this.mail2 = mail2 == null ? null : mail2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.mail3
     *
     * @return the value of vehiclevanagement.mail3
     *
     * @mbggenerated
     */
    public String getMail3() {
        return mail3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.mail3
     *
     * @param mail3 the value for vehiclevanagement.mail3
     *
     * @mbggenerated
     */
    public void setMail3(String mail3) {
        this.mail3 = mail3 == null ? null : mail3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.mail4
     *
     * @return the value of vehiclevanagement.mail4
     *
     * @mbggenerated
     */
    public String getMail4() {
        return mail4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.mail4
     *
     * @param mail4 the value for vehiclevanagement.mail4
     *
     * @mbggenerated
     */
    public void setMail4(String mail4) {
        this.mail4 = mail4 == null ? null : mail4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiclevanagement.mailcount
     *
     * @return the value of vehiclevanagement.mailcount
     *
     * @mbggenerated
     */
    public Integer getMailcount() {
        return mailcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiclevanagement.mailcount
     *
     * @param mailcount the value for vehiclevanagement.mailcount
     *
     * @mbggenerated
     */
    public void setMailcount(Integer mailcount) {
        this.mailcount = mailcount;
    }
}