package com.sh.vehiclemanagement.demo.dao;

import com.sh.vehiclemanagement.demo.entity.VehicleEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int insert(VehicleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int insertSelective(VehicleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    VehicleEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VehicleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiclevanagement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VehicleEntity record);
}